version: '3'
services:
  nodejs-server:
    build:
      context: ./api
    ports:
      - "9000:9000"
    container_name: node-api
  react-ui:
    build:
      context: ./client
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
   
